### ISSUE TITLE
Calling geb.spock report() causes a file not found error in the Report

### ISSUE THREAD

**Issue by rushby** [AOEpeople/geb-spock-reports#15]
I've put together a simple project here:  https://github.com/rushby/geb-spock-reports-test

You see I have commented out the call to "report" method in the spec:

https://github.com/rushby/geb-spock-reports-test/blob/master/src/test/groovy/hbi/specs/browser/GoogleTestSpec.groovy

If I run with that commented out everything is ok - report generates with 1 screenshot for each test run, however put that line back in and the html report show's 2 test runs both with 2 screenshots (which i expect).  Only 1 screenshot is correct for each test run, the other results in an incorrect link to the file.

I'd have expected the 2 screenshots generated from calling report("someStuff") to link through to the screenshots ending -someStuff.  I see that the label on the html report has these extra screenshots labelled as "end".

Let me know if i did something wrong or my understanding is incorrect.

**Comment by rushby** [comment]
My mistake - issue was due to files not being deleted between runs.

**Comment by tilmanginzel** [comment]
Hey @rushby, your understanding is correct. `report("someStuff")` should result in two separate screenshots, as the data table specifies two test runs. The issue is that you need to execute `mvn clean` between consecuitve test runs (same as #8). 

The [GebReportingListener](https://github.com/AOEpeople/geb-spock-reports/blob/master/src/main/groovy/com/aoe/gebspockreports/GebReportingListener.groovy) will be called for each `report` statement. For each call, a `geb-spock-reports.json` file will be appended, containing all the info regarding screenshot paths and the respective feature method. When you change `report`-statements, this file will get out of sync with the actual tests, and therefore the html report may show invalid screenshots or file paths.

Unfortunately, as far as I know there is no way for the library to notice that a spec was re-run, so that old artifacts could be discarded/ignored. I will leave this issue open for now, maybe someone has an idea. In the meantime, the only solution would be to regularly clean the test results, e.g. via `mvn clean`.

**Comment by tilmanginzel** [comment]
Well I typed too slow. ;) Anyway, explanation on why this doesn't work is above.
