### ISSUE TITLE
missing screens when using where-block

### ISSUE THREAD

**Issue by rdmueller** [AOEpeople/geb-spock-reports#18]
It seems that the report has some problems to assign geb artifacts to feature runs when the `where` block is used. At least, only the screenshots of the first run are assigned and the other are listed under "unassigned Geb Artifacts".

If `@Unroll()`-Annotation is used, no artifact can be assigned.

**Comment by tilmanginzel** [comment]
Hey @rdmueller, thanks for the report. I will look into it and see what can be done.

**Comment by tilmanginzel** [comment]
So, my current conclusion is:

* It is possible to correctly assign all artifacts if the `@Unroll` annotation is used, a small fix is necessary for that.
* Unfortunately, when using a data driven `where:` table without the `@Unroll` annotation, it does not seem to be possible to find a clean way to correctly assign the artifacts. For the report listener, each execution just looks like a new feature. I will probably add a note to the readme, that data driven tests with screenshots should be used together with the `@Unroll` annotation, as soon as the fix is implemented

**Comment by rdmueller** [comment]
thanx for the quick analysis.

sounds ok to me 😎

**Comment by tilmanginzel** [comment]
@rdmueller Feel free to test the just released version `0.2.3` :)

**Comment by rdmueller** [comment]
@tilmanginzel thanx for this quick fix! That was awesome :-)
The artifacts are now indeed mapped to the right features when `@Unroll()` is used. 
I still have a problem with the list of unmapped artifacts. It still shows _all_ artifacts. But this might be a problem with my own AsciiDoc template. Have to check it first...

**Comment by tilmanginzel** [comment]
Good to hear that it's working again. :) Is there any way that I can support with the AsciiDoc template?

**Comment by rdmueller** [comment]
thanx. I think I am fine now with the asciidoc template. I now collect a list of assigned artifacts and remove them from the list of unassigned. the result is perfect.

I will give you a ping as soon as it is ready 😀
