### ISSUE TITLE
Geb-Spock-Report is not generated when Jenkins job is aborted.

### ISSUE THREAD

**Issue by BalurQA** [AOEpeople/geb-spock-reports#24]
Hi @tilmanginzel ,

I am running my scripts via Jenkins with time limit of 240 mins, if script execution is not completed within this time, Jenkins aborts the execution. In this case geb-spock-report is not generated.

I would like to see the report for the executed scripts when script execution is aborted by Jenkins.

Thank You

**Comment by tilmanginzel** [comment]
Hi @BalurQA, this is not possible.

This library primarily provides a template for [spock-reports](https://github.com/renatoathaydes/spock-reports), so I have no influence on the point in time when the summary report is being created. spock-reports registers itself as a global [Spock extension](http://spockframework.org/spock/docs/1.0/extensions.html). Once the test execution is done, Spock calls a [stop lifecycle hook](https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/extension/IGlobalExtension.java#L27) on all of its extensions. Only then the summary report can be created.

I assume that the Gradle process is being killed as soon as the timeout is reached in Jenkins, so Spock can never call the stop hook on its extensions. This makes sense, as otherwise it would execute further code which might run indefinitely (far longer than the specified timeout, making it irrelevant).

**Comment by trinidad8516** [comment]
@BalurQA I think you probably want to use Spock @Timout http://spockframework.org/spock/docs/1.3/all_in_one.html#_timeout

**Comment by tilmanginzel** [comment]
Closing this as it's not something that can or should be mitigated in this library.
