### ISSUE TITLE
reporting from setupSpec/cleanupSpec

### ISSUE THREAD

**Issue by rosemead** [AOEpeople/geb-spock-reports#6]
Hi. 
If you could take a look at https://github.com/rosemead/testreport1:

I've subclassed GebReportingSpec to allow creating reports from setup/cleanupSpec. I think I've got all my ducks in a row in terms of file locations & naming convention. But the reports aren't added onto the html report.

Would appreciate your feedback. Cheers

**Comment by tilmanginzel** [comment]
Hi,

I will try to take a look soon. Just for clarification: Are only the setup/cleanup reports missing, or all reports?

**Comment by rosemead** [comment]
Thanks. Yes, it is the reports generated in setup/cleanupSpec that are missing from the html report.
Forgot to mention : 'mvn verify' to execute the project, should you wish to see the results first-hand.

**Comment by tilmanginzel** [comment]
So, this is a tricky one. 

While the file location and naming conventions are correct, they never get picked up by the [spec-template.html](https://github.com/AOEpeople/geb-spock-reports/blob/master/src/main/resources/templates/spec-template.html#L124). This is because the setup/cleanup methods are not interpreted as _features_. Only test methods are features. The list of executed features is provided by the parent library, spock-reports. So there's no way to map those setup/cleanup methods and their respective screenshots to a feature.

The only possible solution I see is the following:
The generated html report could have an extra area for all screenshots which could not be mapped to a specific feature. This could be either at the top or bottom of the report and simply lists all remaining screenshots. This would also be helpful if other problems (e.g. bad method naming) leads to an impossible mapping of a screenshot to a feature.

What do you think about that?

**Comment by rosemead** [comment]
Sounds great. Thumbs-up from me.

**Comment by tilmanginzel** [comment]
Hi, so I just pushed a commit which fixes this issue. 

While it's not really beautiful, the following area is now added to the html report. It was much easier to append it at the end of the report instead of the beginning, hope you don't mind.

<img width="810" alt="grafik" src="https://user-images.githubusercontent.com/3899565/36644578-97075aec-1a5c-11e8-8cb5-50a7ac218dd8.png">

I hope to publish a new version till the end of next week, after I fixed your other issue #7.

**Comment by tilmanginzel** [comment]
By the way, after this is published your custom [report](https://github.com/rosemead/testreport1/blob/master/src/test/groovy/foo/MySpecBase.groovy#L31) function is not necessary anymore. You can simply call `browser.report("label")` from setupSpec/cleanupSpec. ;)

**Comment by rosemead** [comment]
super! looking forward to it. Thanks heaps!

**Comment by tilmanginzel** [comment]
Published in [v0.1.5](https://bintray.com/aoepeople/libraries/geb-spock-reports/0.1.5).
