### ISSUE TITLE
stale links in html report after re-running a spec

### ISSUE THREAD

**Issue by rosemead** [AOEpeople/geb-spock-reports#8]
E.G., if I
* execute a set of tests, among-which is TestFoo, which fails.
* fix and re-run TestFoo. Spec passes.
* inspect TestFoo.html. 
Report contains links to "failure" screenshots, apparently from the preceding failed run.

If I delete `geb-report-info.json` before rerunning the fixed spec, the html report is fine.

**Comment by tilmanginzel** [comment]
Hey @rosemead,

this is a known issue for which I don't know any solution. I would recommend to run `./gradlew clean` before executing the tests again if you want to have a clean report.

Unfortunately, as far as I know there is no way for the GebReportingListener to notice that a spec was re-run, so that old artifacts could be discarded. Do you have any idea?

**Comment by tilmanginzel** [comment]
I will close the issue as it is currently not possible to solve this. There is now a [note](https://github.com/AOEpeople/geb-spock-reports#caveats) in the readme to make aware of it.

Feel free to re-open if new ideas on possible fixes come up.
